import './globals.css'
import { Inter } from 'next/font/google'
import Navbar from "@/app/components/Navbar";
import Footer from "@/app/components/Footer";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Prince's Blog,
  description: 'Generated by Next JS',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className='bg-white'>
      <body className={inter.className}>
      <Navbar/>
      {children}
      <Footer/>
      </body>
    </html>
  )
}
